# Generated by Django 5.0.6 on 2024-07-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.membershipplan'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
