# Generated by Django 5.0.6 on 2024-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_enrollment_selectmembershipplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
