# Generated by Django 5.0.6 on 2024-07-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_enrollment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipPlan',
            field=models.CharField(max_length=50),
        ),
    ]
