# Generated by Django 5.0.6 on 2024-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_gallery_alter_membershipplan_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selectdate', models.DateTimeField(auto_now_add=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('Login', models.CharField(max_length=100)),
                ('Logout', models.CharField(max_length=100)),
                ('SelectWorkout', models.CharField(max_length=100)),
                ('TrainedBy', models.CharField(max_length=100)),
            ],
        ),
    ]
